const PERMISSIONS = {
  // Jobs
  VIEW_JOB: 'VIEW_JOB',
  CREATE_JOB: 'CREATE_JOB',
  UPDATE_JOB: 'UPDATE_JOB',
  UPDATE_JOB_STATUS: 'UPDATE_JOB_STATUS',
  ADD_JOB_COMMENT: 'ADD_JOB_COMMENT',
  REASSIGN_JOB: 'REASSIGN_JOB',
  ASSIGN_RECURRING_JOB: 'ASSIGN_RECURRING_JOB',
  WHITELIST_CLIENT_COMMENT: 'WHITELIST_CLIENT_COMMENT',

  // Visits
  CREATE_VISIT: 'CREATE_VISIT',
  VIEW_VISIT: 'VIEW_VISIT',
  UPDATE_VISIT: 'UPDATE_VISIT',
  START_VISIT: 'START_VISIT',
  SUBMIT_VISIT: 'SUBMIT_VISIT',
  APPROVE_VISIT: 'APPROVE_VISIT',

  // Contacts
  VIEW_CONTACT: 'VIEW_CONTACT',
  CREATE_CONTACT: 'CREATE_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',

  // Booking
  CREATE_BOOKING: 'CREATE_BOOKING',
  VIEW_BOOKING: 'VIEW_BOOKING',
  UPDATE_BOOKING: 'UPDATE_BOOKING',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  ARCHIVE_BOOKING: 'ARCHIVE_BOOKING',

  // System
  VIEW_USER: 'VIEW_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  CREATE_ROLE: 'CREATE_ROLE',
  VIEW_ROLE: 'VIEW_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  VIEW_BRANCH: 'VIEW_BRANCH',
  CREATE_BRANCH: 'CREATE_BRANCH',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
  DELETE_BRANCH: 'DELETE_BRANCH',
  ASSIGN_BRANCH_ADMIN: 'ASSIGN_BRANCH_ADMIN',
  UPDATE_BRANCH_ADMIN: 'UPDATE_BRANCH_ADMIN',
  DELETE_BRANCH_ADMIN: 'DELETE_BRANCH_ADMIN',

  // Analytics - for future use
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_BRANCH_ANALYTICS: 'VIEW_BRANCH_ANALYTICS',
  VIEW_GLOBAL_ANALYTICS: 'VIEW_GLOBAL_ANALYTICS',
};

module.exports = PERMISSIONS;
